services:

    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
            - ./storage/logs/supervisor:/var/log/supervisor
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    db:
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'

    mail:
        image: axllent/mailpit:latest
        ports:
        - 8025:8025
        - 1025:1025

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - .docker/redis/data:/data
        ports:
        - 6379:6379

    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        container_name: soketi
        ports:
            - 6001:6001
        environment:
            - SOKETI_DEBUG=1
            - SOKETI_PORT=6001
            - SOKETI_METRICS_SERVER_PORT=9601
            - SOKETI_DEFAULT_APP_ID=app
            - SOKETI_DEFAULT_APP_KEY=app-key
            - SOKETI_DEFAULT_APP_SECRET=app-secret
            - SOKETI_CORS_ALLOWED_ORIGINS=*
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - php
        restart: unless-stopped
